site_name: AI Applied education
site_description: A program to teach practical programming and data science skills, preparing you for tech and job challenges in any career.
repo_url: https://github.com/charlstown/ai-applied-education
site_author: charlstown

# Configuration
# Theme
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight 
  language: en

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: teal]
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


# Sorting menu pages
nav:
    - Home: 'index.md'
    - Unit 1:
      - 1.1 Introduction to Python: 'program/unit-1/11-introduction-to-python.md'
      - 1.2 Introduction to GitHub: 'program/unit-1/12-Introduction-to-gitHub.md'
      - 1.3 Practice with Python and GitHub I: 'program/unit-1/13-practice-with-python-and-github-I.md'
      - 1.3 Practice with Python and GitHub II: 'program/unit-1/14-practice-with-python-and-gitHub-II.md'
      - 1.5 Dialogue with a Professional: 'program/unit-1/15-dialogue-with-a-professional.md'
    - Unit 2:
      - 2.1 Current Context and Application of Mathematical Models in AI: 'program\unit-2\21-current-context-and-application-of-mathematical-models-in-ai.md'
      - 2.2 Introduction to Visualization and Descriptive Statistics: 'program\unit-2\22-introduction-to-visualization-and-descriptive-statistics.md'
      - 2.3 Introduction to Exploratory Data Analysis (EDA): 'program\unit-2\23-introduction-to-exploratory-data-analysis-(eda).md'
      - 2.4 Data Cleaning and Processing: 'program\unit-2\24-data-cleaning-and-processing.md'
      - 1.5 Dialogue with a Professional: 'program/unit-2/25-dialogue-with-a-professional.md'
    - Contact: 'getting-started.md' # getting started


# Extensions
markdown_extensions:
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search
  - markdownextradata

# css
extra_css:
  - assets/stylesheets/extra.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js

# Copyright message
copyright: Copyright &copy; AI Applied Education - 2023

# Global variables
extra:
  links:
    self-host: 'url'
    learning-host: 'url'
